model:
  name: sfm_backend
  fusion: sum   # or learnable
data:
  name: data_utils
  n_mels: 64
  n_fft: 512
  hop_length: 160
  win_length: 400
  fmin: 20
  fmax: 7600
  mean_norm: true
  std_norm: true
